baseurl: 'https://haimanifesto.org'
permalink: pretty
title: 'AI:M'

logo:
  mobile: "images/logo/aim-scorecard-mobile.svg"
  mobile_height: "50px"
  mobile_width: "50px"
  desktop: "images/logo/aim-scorecard.svg"
  desktop_height: "50px"
  desktop_width: "50px"

home: 
  limit_services: 6

collections:
  services:
    output: true
    sort_by: weight
  team:
    output: true
  scorecards:
    output: true
    sort_by: weight

defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"
  - scope:
      path: ""
      type: "scorecards"
    values:
      layout: "scorecard"

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md